### PR TITLE
Add Companies from Tech In Scotland

### PR DESCRIPTION
**Pull request by jarofgreen**
This adds the export of companies with the tag PHP from https://find.techin.scot/companies/ to the site.

companies1

And with more clicked:

companies2

### CODE REVIEW

**Comment by dragoonis** [comment]
Now that we've taken a few companies from https://find.techin.scot/companies, it says please visit Tech In Scotland website, but people shouldn't have to visit that website, but instead just make a PR here.

**Comment by jarofgreen** [comment]
Well, Tech In Scotland is the source of the data. So that's where ppl go to update the data. The same model as events from Open Tech Calendar.

This way, the data can be updated by a easy to use web interface that non-tech ppl can use, and coding and PR skills are not required.

Also, the data becomes part of a larger data set that is managed on Tech In Scotland and network effects start to come into play. This will help with the biggest problem - making sure the data is kept up to date. Also, on TiS we will be doing things to try and help with this (eg prompt emails) in the same kind of way we already do on OTC.

You could start your own data store here, but that would be splitting the data store and raising problems about keeping it up to date. If you have a specific problem with something Tech In Scotland is doing happy to discuss, but with my experience of running community data sets I think this is the best chance of getting this to critical mass.

**Comment by jarofgreen** [comment]
ps. If you want to remove the words "Tech In Scotland" from the link and just have it say "To add a new entry for free or edit, please go here and make sure the PHP tag is selected!" or something that's fine with me.

**Comment by dragoonis** [comment]
@jarofgreen no issues with TiS. 

Since our website isn't synced with TiS, can we remove their company address please, it's just more maintenance needed and potential mis-information we're conveying.

Links to their website (and to the TiS website respectively) would be of value though. On their own personal website they can maintain their address there and that's a good (and reliable) source of information.

**Comment by jarofgreen** [comment]
> Since our website isn't synced with TiS,

It is.

See this Javascript tag - this is how the data is loaded.

`<script src="https://find.techin.scot/api1/companies.techused-kpxq.js"></script>
`

It's at the bottom of index.html

Happy to remove address for display reasons, but I thought readers would like to see which city they are in tho.

**Comment by dragoonis** [comment]
@jarofgreen after reviewing the code more in-depth now I see it's being pulled by JS. In that case keep the address since it's synced with TiS

**Comment by dragoonis** [comment]
@jarofgreen functionally it's sound but we have to address the issue of design. Right now it's grey text on grey BG. 

If you look at the design on the homepage section that currently says: `Join the worldwide PHP community for the second ScotlandPHP conference`, that white BG with black and blue text, would be a suitable design for this page. Are you able to match that design to this page?

**Comment by jarofgreen** [comment]
I'm honestly not sure where you are seeing that text - can you send a URL?

I have put it in a white box tho, to match the other sections - user groups and events. That is better, thanks.

companies3

ps. Personally I would like to change the style of links - I think for UI reasons there should be some highlight on them when not hovered/focused, but as that applies to the whole site and not just the companies section that's an issue for another pull request.

**Comment by dragoonis** [comment]
It's on the homepage: https://conference.scotlandphp.co.uk/

**Comment by jarofgreen** [comment]
Ah, I see. Well, as it stands the style of the text and links in the companies section matches other sections on that page - it's better that it's consistent and that's really as far as I can go here. Another pull request could tackle overall style if that was wanted.

**Comment by tdutrion** [comment]
I'm all good with the proposed design, changing to something similar to the conference website should indeed be part of a communication strategy, and for the time being none of us has enough time to think and act on this...

Thanks for this PR @jarofgreen!

**Pull request merged**
